import { createBrowserClient } from "@supabase/ssr";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export function createClient() {
  return createBrowserClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}

/**
 * @supabase/ssr's createBrowserClient hard-codes flowType: "pkce"
 * internally — it ignores any flowType passed in options, so it can't
 * be configured away. That's a problem specifically for
 * signInWithOtp: magic links get opened wherever the email client
 * decides (a new tab, a different device, or — very commonly on
 * mobile — an in-app browser with its own isolated cookie jar), and
 * PKCE requires the code_verifier generated by the *requesting*
 * client to still be readable by whatever opens the link. When it
 * isn't, exchangeCodeForSession fails with "PKCE code verifier not
 * found in storage".
 *
 * Use this plain (non-cookie-persisted) client just for requesting
 * the OTP email — implicit flow embeds everything the callback needs
 * directly in the link, so it doesn't depend on shared storage at
 * all. The actual session, once the link is clicked, is still
 * established via the cookie-backed client above (see
 * app/auth/callback/page.tsx), so the server can see it normally.
 */
export function createOtpClient() {
  return createSupabaseClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      auth: {
        flowType: "implicit",
        persistSession: false,
        detectSessionInUrl: false,
      },
    }
  );
}
